#############################
## CONFIGURAZIONE STANDARD ##
#############################

# simulazione bilanciata

# 30 giorni simulati
SIM_DURATION = 30

# durata reale di un minuto simulato (in nanosecondi)
# es: 100ms reali = 1 minuto simulato -> 100000000
N_NANO_SECS = 100000000

# popolazione
NOF_USERS = 40
NOF_WORKERS = 6
NOF_TABLE_SEATS = 30

# utenti in attesa a fine giornata
# > 10 utenti fuori => termina per overload
OVERLOAD_THRESHOLD = 10

# tempi di servizio
AVG_SRVC_PRIMI = 5000
AVG_SRVC_MAIN_COURSE = 6000
AVG_SRVC_COFFEE = 2000
AVG_SRVC_CASSA = 3000

# capacità code (posti in piedi prima del servizio)
NOF_WK_SEATS_PRIMI = 10
NOF_WK_SEATS_SECONDI = 10
NOF_WK_SEATS_COFFEE = 15
NOF_WK_SEATS_CASSA = 15

# prezzi
PRICE_PRIMI = 5
PRICE_SECONDI = 8
PRICE_COFFEE = 1

# rifornimenti
AVG_REFILL_PRIMI = 50000
AVG_REFILL_SECONDI = 50000
MAX_PORZIONI_PRIMI = 100
MAX_PORZIONI_SECONDI = 100