#############################
## CONFIGURAZIONE OVERLOAD ##
#############################

# termina perché troppi utenti sono in coda a fine giornata
# Strategia: Tanti utenti, servizio lento (+ probabilità di 
# fare pause), pochi posti.

SIM_DURATION = 30

# durata reale di un minuto simulato (in nanosecondi)
# es: 100ms reali = 1 minuto simulato -> 100000000
N_NANO_SECS = 100000000

# tanti utenti
NOF_USERS = 200
# pochi lavoratori
NOF_WORKERS = 4
# basta 1 utente insoddisfatto per terminare
OVERLOAD_THRESHOLD = 1

# tempi di servizio LENTISSIMI
AVG_SRVC_PRIMI = 500000
AVG_SRVC_MAIN_COURSE = 600000
AVG_SRVC_COFFEE = 200000
AVG_SRVC_CASSA = 300000

# postazioni fisiche operatori
WORKSTATIONS_PRIMI = 5
WORKSTATIONS_SECONDI = 5
WORKSTATIONS_COFFEE = 5
WORKSTATIONS_CASSA = 1

# pause operatori
MAX_PAUSES_PER_DAY = 3
PAUSE_DURATION_NS = 500000000
PAUSE_PROBABILITY_PERCENT = 30

# variabilità tempi servizio (+/- %)
VARIABILITY_PRIMI = 50
VARIABILITY_SECONDI = 50
VARIABILITY_COFFEE = 80
VARIABILITY_CASSA = 10

# code corte
NOF_WK_SEATS_PRIMI = 2
NOF_WK_SEATS_SECONDI = 2
NOF_WK_SEATS_COFFEE = 2
NOF_WK_SEATS_CASSA = 2

NOF_TABLE_SEATS = 10

PRICE_PRIMI = 5
PRICE_SECONDI = 8
PRICE_COFFEE = 1

AVG_REFILL_PRIMI = 50000
AVG_REFILL_SECONDI = 50000
MAX_PORZIONI_PRIMI = 100
MAX_PORZIONI_SECONDI = 100