#############################
## CONFIGURAZIONE OVERLOAD ##
#############################

# 1) SIMULAZIONE GLOBALE

SIM_DURATION = 30
N_NANO_SECS = 100000000
DAILY_SERVICE_MINUTES = 60
SYSTEM_STARTUP_DELAY_SEC = 2

# basta 15 solo utenti respinti/fuori tempo per scatenare l'overload
OVERLOAD_THRESHOLD = 15

# 2) POPOLAZIONE E RISORSE

# moltissimi utenti
NOF_USERS = 150
# pochi lavoratori
NOF_WORKERS = 4
# pochissimi tavoli (collo di bottiglia finale)
NOF_TABLE_SEATS = 5
AVG_USER_W_TICKET = 80

# 3) CONFIGURAZIONE STAZIONI

# code minuscole: si riempiono subito => utenti respinti
NOF_WK_SEATS_PRIMI = 2
NOF_WK_SEATS_SECONDI = 2
NOF_WK_SEATS_CAFFE = 2
NOF_WK_SEATS_CASSA = 2

TICKET_READER_CAPACITY = 2
# 2s
TICKET_READER_TIMEOUT_NS = 2000000000

# poche postazioni fisiche
WORKSTATIONS_PRIMI = 2
WORKSTATIONS_SECONDI = 2
WORKSTATIONS_CAFFE = 2
WORKSTATIONS_CASSA = 1

# 4) METRICHE DI SERVIZIO

# servizio lentissimo
AVG_SRVC_PRIMI = 500000000
AVG_SRVC_SECONDI = 600000000
AVG_SRVC_CAFFE = 300000000
AVG_SRVC_CASSA = 400000000

VARIABILITY_PRIMI = 50
VARIABILITY_SECONDI = 50
VARIABILITY_CAFFE = 80
VARIABILITY_CASSA = 10

PRICE_PRIMI = 5.5
PRICE_SECONDI = 8.2
PRICE_CAFFE = 1.2

TICKET_DISCOUNT_PERCENT = 25.0

# 5) COMPORTAMENTO OPERATORI

# operatori sfaticati: tante pause lunghe
MAX_PAUSES_PER_DAY = 10
PAUSE_DURATION_NS = 5000000000
PAUSE_PROBABILITY_PERCENT = 80
DAY_END_BARRIER_WAIT_SEC = 30

# 6) COMPORTAMENTO E PREFERENZE UTENTI

# utenti impazienti (1 secondo timeout)
USER_QUEUE_TIMEOUT_SEC = 1
# mangiano molto lentamente (tengono i tavoli occupati)
USER_MEAL_DURATION_NS = 5000000000
USER_COFFEE_DURATION_NS = 10000000
# arrivano un po più lentamente
USER_MAX_ARRIVAL_DELAY_US = 500000

PROBABILITY_USER_WANTS_PRIMO = 100
PROBABILITY_USER_WANTS_SECONDO = 100
PROBABILITY_USER_WANTS_CAFFE = 100

# budget utenti
USER_BUDGET_MIN = 50
USER_BUDGET_MAX = 150
USER_MIN_DAILY_SALARY = 20
USER_MAX_DAILY_SALARY = 40

# 7) LOGISTICA

REFILL_INTERVAL_MINUTES = 10
AVG_REFILL_PRIMI = 0
AVG_REFILL_SECONDI = 10
MAX_PORZIONI_PRIMI = 30
MAX_PORZIONI_SECONDI = 100
MAX_PORZIONI_CAFFE = 10000

# 8) TOOLS
DEFAULT_SCIOPERO_STOP_DURATION = 60

EXPORT_FOLDER_PATH = reports/

EXPORT_DAILY_REPORTS_CSV = 1
DAILY_REPORTS_FILENAME_CSV = daily_report

EXPORT_FINAL_STATS_CSV = 1
FINAL_STATS_FILENAME_CSV = final_stats