################################
##  CONFIGURAZIONE SAFE LOAD  ##
##   (250 Utenti - Stabile)   ##
################################

# 1) SIMULAZIONE GLOBALE
SIM_DURATION = 30
# 1 minuto simulato = 0.2ms (Molto veloce, ma gestibile grazie ai timeout alti)
N_NANO_SECS = 200000
DAILY_SERVICE_MINUTES = 180 

SYSTEM_STARTUP_DELAY_SEC = 4

# > NOF_USERS
OVERLOAD_THRESHOLD = 300

# 2) POPOLAZIONE E RISORSE
NOF_USERS = 250
NOF_WORKERS = 50
NOF_TABLE_SEATS = 250
AVG_USER_W_TICKET = 80

# 3) CONFIGURAZIONE STAZIONI
# code "Infinite"
NOF_WK_SEATS_PRIMI = 200
NOF_WK_SEATS_SECONDI = 200
NOF_WK_SEATS_CAFFE = 300
NOF_WK_SEATS_CASSA = 300

TICKET_READER_CAPACITY = 25
TICKET_READER_TIMEOUT_NS = 100000000

# RISORSE FISICHE (Massimizzate)
# totale 50 workers:
WORKSTATIONS_PRIMI = 15
WORKSTATIONS_SECONDI = 15
WORKSTATIONS_CAFFE = 5
WORKSTATIONS_CASSA = 15

# 4) METRICHE DI SERVIZIO
AVG_SRVC_PRIMI = 60000000
AVG_SRVC_SECONDI = 80000000
AVG_SRVC_CAFFE = 20000000
AVG_SRVC_CASSA = 30000000

VARIABILITY_PRIMI = 10
VARIABILITY_SECONDI = 10
VARIABILITY_CAFFE = 10
VARIABILITY_CASSA = 10

PRICE_PRIMI = 6.0
PRICE_SECONDI = 9.0
PRICE_CAFFE = 1.2
TICKET_DISCOUNT_PERCENT = 20.0

# 5) COMPORTAMENTO OPERATORI
MAX_PAUSES_PER_DAY = 1
# 10ms
PAUSE_DURATION_NS = 10000000
PAUSE_PROBABILITY_PERCENT = 0
DAY_END_BARRIER_WAIT_SEC = 120

# 6) COMPORTAMENTO E PREFERENZE UTENTI
# pazienza "Infinita"
USER_QUEUE_TIMEOUT_SEC = 100

USER_MEAL_DURATION_NS = 1000000000
USER_COFFEE_DURATION_NS = 100000000

USER_MAX_ARRIVAL_DELAY_US = 90000000

PROBABILITY_USER_WANTS_PRIMO = 80
PROBABILITY_USER_WANTS_SECONDO = 80
PROBABILITY_USER_WANTS_CAFFE = 30

USER_BUDGET_MIN = 2
USER_BUDGET_MAX = 20
USER_MIN_DAILY_SALARY = 5
USER_MAX_DAILY_SALARY = 10

# 7) LOGISTICA
REFILL_INTERVAL_MINUTES = 30
AVG_REFILL_PRIMI = 50
AVG_REFILL_SECONDI = 50
MAX_PORZIONI_PRIMI = 100
MAX_PORZIONI_SECONDI = 100
MAX_PORZIONI_CAFFE = 1000

# 8) TOOLS
EXPORT_FOLDER_PATH = reports/
EXPORT_DAILY_REPORTS_CSV = 0
DAILY_REPORTS_FILENAME_CSV = days/safe_daily
EXPORT_FINAL_STATS_CSV = 1
FINAL_STATS_FILENAME_CSV = safe_final