################################
##  CONFIGURAZIONE SAFE LOAD  ##
##   (FINAL STABLE VERSION)   ##
################################

# 1) SIMULAZIONE GLOBALE
SIM_DURATION = 30
N_NANO_SECS = 50000000
DAILY_SERVICE_MINUTES = 180

SYSTEM_STARTUP_DELAY_SEC = 2
OVERLOAD_THRESHOLD = 800

# 2) POPOLAZIONE
NOF_USERS = 250
NOF_WORKERS = 50
NOF_TABLE_SEATS = 300
AVG_USER_W_TICKET = 80

# 3) CONFIGURAZIONE STAZIONI
NOF_WK_SEATS_PRIMI = 250
NOF_WK_SEATS_SECONDI = 250
NOF_WK_SEATS_CAFFE = 300
NOF_WK_SEATS_CASSA = 300

TICKET_READER_CAPACITY = 25
TICKET_READER_TIMEOUT_NS = 100000000

# RISORSE FISICHE
WORKSTATIONS_PRIMI = 15
WORKSTATIONS_SECONDI = 15
WORKSTATIONS_CAFFE = 4
WORKSTATIONS_CASSA = 16

# 4) METRICHE DI SERVIZIO
AVG_SRVC_PRIMI = 120000000
AVG_SRVC_SECONDI = 150000000
AVG_SRVC_CAFFE = 40000000
AVG_SRVC_CASSA = 60000000

VARIABILITY_PRIMI = 10
VARIABILITY_SECONDI = 10
VARIABILITY_CAFFE = 10
VARIABILITY_CASSA = 10

PRICE_PRIMI = 6.0
PRICE_SECONDI = 9.0
PRICE_CAFFE = 1.2
TICKET_DISCOUNT_PERCENT = 20.0

# 5) COMPORTAMENTO OPERATORI
MAX_PAUSES_PER_DAY = 1
PAUSE_DURATION_NS = 500000000
PAUSE_PROBABILITY_PERCENT = 5
DAY_END_BARRIER_WAIT_SEC = 60

# 6) UTENTI
USER_QUEUE_TIMEOUT_SEC = 8

USER_MEAL_DURATION_NS = 1000000000
USER_COFFEE_DURATION_NS = 250000000
USER_MAX_ARRIVAL_DELAY_US = 5000000

PROBABILITY_USER_WANTS_PRIMO = 80
PROBABILITY_USER_WANTS_SECONDO = 80
PROBABILITY_USER_WANTS_CAFFE = 30

USER_BUDGET_MIN = 50
USER_BUDGET_MAX = 100
USER_MIN_DAILY_SALARY = 0
USER_MAX_DAILY_SALARY = 0

# 7) LOGISTICA
REFILL_INTERVAL_MINUTES = 30
AVG_REFILL_PRIMI = 100
AVG_REFILL_SECONDI = 100
MAX_PORZIONI_PRIMI = 300
MAX_PORZIONI_SECONDI = 300
MAX_PORZIONI_CAFFE = 2000

# 8) TOOLS
EXPORT_FOLDER_PATH = reports/
EXPORT_DAILY_REPORTS_CSV = 1
DAILY_REPORTS_FILENAME_CSV = days/safe_daily
EXPORT_FINAL_STATS_CSV = 1
FINAL_STATS_FILENAME_CSV = safe_final