############################
## CONFIGURAZIONE TIMEOUT ##
############################

# 1) SIMULAZIONE GLOBALE

# durata breve per testare la fine naturale
SIM_DURATION = 15
N_NANO_SECS = 100000
DAILY_SERVICE_MINUTES = 60
SYSTEM_STARTUP_DELAY_SEC = 1

# soglia altissima: difficile andare in overload
OVERLOAD_THRESHOLD = 500

# 2) POPOLAZIONE E RISORSE

# pochi utenti
NOF_USERS = 50
# tanti lavoratori
NOF_WORKERS = 4
# tavoli infiniti
NOF_TABLE_SEATS = 50
AVG_USER_W_TICKET = 80

# 3) CONFIGURAZIONE STAZIONI

# code enormi: nessuno viene respinto
NOF_WK_SEATS_PRIMI = 1
NOF_WK_SEATS_SECONDI = 1
NOF_WK_SEATS_CAFFE = 1
NOF_WK_SEATS_CASSA = 1

TICKET_READER_CAPACITY = 2
TICKET_READER_TIMEOUT_NS = 500000000

# abbondanza di postazioni
WORKSTATIONS_PRIMI = 1
WORKSTATIONS_SECONDI = 1
WORKSTATIONS_CAFFE = 1
WORKSTATIONS_CASSA = 1

# 4) METRICHE DI SERVIZIO

# servizio lentissimo
AVG_SRVC_PRIMI = 2000000000
AVG_SRVC_SECONDI = 3000000000
AVG_SRVC_CAFFE = 1500000000
AVG_SRVC_CASSA = 1000000000

VARIABILITY_PRIMI = 0
VARIABILITY_SECONDI = 0
VARIABILITY_CAFFE = 0
VARIABILITY_CASSA = 0

PRICE_PRIMI = 5.5
PRICE_SECONDI = 8.2
PRICE_CAFFE = 1.2

TICKET_DISCOUNT_PERCENT = 25.0

# 5) COMPORTAMENTO OPERATORI

# lavoratori stakanovisti (niente pause)
MAX_PAUSES_PER_DAY = 0
PAUSE_DURATION_NS = 0
PAUSE_PROBABILITY_PERCENT = 0
DAY_END_BARRIER_WAIT_SEC = 30

# 6) COMPORTAMENTO E PREFERENZE UTENTI

# utenti molto pazienti (10 secondi attesa)
USER_QUEUE_TIMEOUT_SEC = 1
# mangiano veloce
USER_MEAL_DURATION_NS = 5000000
USER_COFFEE_DURATION_NS = 100000
# arrivo utenti di massa
USER_MAX_ARRIVAL_DELAY_US = 100000

PROBABILITY_USER_WANTS_PRIMO = 100
PROBABILITY_USER_WANTS_SECONDO = 0
PROBABILITY_USER_WANTS_CAFFE = 0

# budget utenti alti
USER_BUDGET_MIN = 50
USER_BUDGET_MAX = 100
USER_MIN_DAILY_SALARY = 20
USER_MAX_DAILY_SALARY = 50

# 7) LOGISTICA

REFILL_INTERVAL_MINUTES = 10
AVG_REFILL_PRIMI = 1000
AVG_REFILL_SECONDI = 1000
MAX_PORZIONI_PRIMI = 1000
MAX_PORZIONI_SECONDI = 1000
MAX_PORZIONI_CAFFE = 1000

# 8) TOOLS
DEFAULT_SCIOPERO_STOP_DURATION = 60

EXPORT_FOLDER_PATH = reports/

EXPORT_DAILY_REPORTS_CSV = 1
DAILY_REPORTS_FILENAME_CSV = daily_report

EXPORT_FINAL_STATS_CSV = 1
FINAL_STATS_FILENAME_CSV = final_stats