############################
## CONFIGURAZIONE TIMEOUT ##
############################

# 1) SIMULAZIONE GLOBALE

# durata breve per testare la fine naturale
SIM_DURATION = 5
N_NANO_SECS = 100000000
DAILY_SERVICE_MINUTES = 120
SYSTEM_STARTUP_DELAY_SEC = 2

# soglia altissima: difficile andare in overload
OVERLOAD_THRESHOLD = 50

CASSA_POSITION = USCITA

# 2) POPOLAZIONE E RISORSE

# pochi utenti
NOF_USERS = 10
# tanti lavoratori
NOF_WORKERS = 10
# tavoli infiniti
NOF_TABLE_SEATS = 100

# 3) CONFIGURAZIONE STAZIONI

# code enormi: nessuno viene respinto
NOF_WK_SEATS_PRIMI = 50
NOF_WK_SEATS_SECONDI = 50
NOF_WK_SEATS_COFFEE = 50
NOF_WK_SEATS_CASSA = 50

# abbondanza di postazioni
WORKSTATIONS_PRIMI = 5
WORKSTATIONS_SECONDI = 5
WORKSTATIONS_COFFEE = 5
WORKSTATIONS_CASSA = 2

# 4) METRICHE DI SERVIZIO

# servizio fulmineo
AVG_SRVC_PRIMI = 1000
AVG_SRVC_SECONDI = 1000
AVG_SRVC_COFFEE = 500
AVG_SRVC_CASSA = 500

VARIABILITY_PRIMI = 10
VARIABILITY_SECONDI = 10
VARIABILITY_COFFEE = 10
VARIABILITY_CASSA = 10

PRICE_PRIMI = 5
PRICE_SECONDI = 8
PRICE_COFFEE = 1

# 5) COMPORTAMENTO OPERATORI

# lavoratori stakanovisti (niente pause)
MAX_PAUSES_PER_DAY = 0
PAUSE_DURATION_NS = 0
PAUSE_PROBABILITY_PERCENT = 0

# 6) COMPORTAMENTO E PREFERENZE UTENTI

# utenti molto pazienti (10 secondi attesa)
USER_QUEUE_TIMEOUT_SEC = 10
# mangiano veloce
USER_MEAL_DURATION_NS = 10000000
# arrivo scaglionato bene
USER_MAX_ARRIVAL_DELAY_US = 2000000

PROBABILITY_USER_WANTS_PRIMO = 50
PROBABILITY_USER_WANTS_SECONDO = 50
PROBABILITY_USER_WANTS_COFFEE = 20

# 7) LOGISTICA

AVG_REFILL_PRIMI = 10000
AVG_REFILL_SECONDI = 10000
MAX_PORZIONI_PRIMI = 500
MAX_PORZIONI_SECONDI = 500