graph TD
  RESP[Responsabile] -->|`fork` + `execve`| WORKERS[Workers P/S/C]
  RESP -->|`fork` + `execve`| USERS[Utenti]
  
  subgraph IPC Resources
    SHM[(Shared Memory)]
    SEM{Semafori}
    MSG[Coda Messaggi]
  end

  WORKERS <-->|Read/Write| SHM
  WORKERS <-->|Wait/Signal| SEM
  WORKERS <-->|Send/Receive| MSG

  USERS <-->|Send/Receive| MSG
  USERS <-->|Wait/Signal| SEM
  USERS -.->|Read Only| SHM